project_id = "o11y-resolve-storage-public-bucket"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = false

[storage]
enabled = true
