project_id = "o11y-resolve-storage-cors-wildcard"

[auth]
enabled = false

[storage]
enabled = true

[storage.image_transformation]
enabled = false

[storage.s3_protocol]
enabled = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[inbucket]
enabled = false
